# Generated by Django 4.1.7 on 2023-03-17 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'questions'},
        ),
        migrations.AddField(
            model_name='questions',
            name='division_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 17, 37, 54, 404993)),
        ),
    ]
