# Generated by Django 4.1.7 on 2023-03-17 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_company_options_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.company'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 17, 42, 20, 548735)),
        ),
    ]
