# Generated by Django 4.1.7 on 2023-03-17 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_questions_company_alter_questions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 18, 6, 6, 28069)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
