# Generated by Django 4.1.7 on 2023-03-17 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_questions_date_time_alter_questions_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='no_name_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 21, 24, 58, 875082)),
        ),
    ]
