# Generated by Django 4.1.7 on 2023-03-18 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_questions_no_name_company_alter_questions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 8, 56, 33, 934077)),
        ),
    ]
